/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as PackageRouteImport } from './routes/package'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CargoIdRouteImport } from './routes/cargo.$id'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoIdRoute = CargoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CargoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRouteWithChildren
  '/login': typeof LoginRoute
  '/package': typeof PackageRoute
  '/warehouse': typeof WarehouseRoute
  '/cargo/$id': typeof CargoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRouteWithChildren
  '/login': typeof LoginRoute
  '/package': typeof PackageRoute
  '/warehouse': typeof WarehouseRoute
  '/cargo/$id': typeof CargoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cargo': typeof CargoRouteWithChildren
  '/login': typeof LoginRoute
  '/package': typeof PackageRoute
  '/warehouse': typeof WarehouseRoute
  '/cargo/$id': typeof CargoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cargo'
    | '/login'
    | '/package'
    | '/warehouse'
    | '/cargo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cargo' | '/login' | '/package' | '/warehouse' | '/cargo/$id'
  id:
    | '__root__'
    | '/'
    | '/cargo'
    | '/login'
    | '/package'
    | '/warehouse'
    | '/cargo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargoRoute: typeof CargoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PackageRoute: typeof PackageRoute
  WarehouseRoute: typeof WarehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package': {
      id: '/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo/$id': {
      id: '/cargo/$id'
      path: '/$id'
      fullPath: '/cargo/$id'
      preLoaderRoute: typeof CargoIdRouteImport
      parentRoute: typeof CargoRoute
    }
  }
}

interface CargoRouteChildren {
  CargoIdRoute: typeof CargoIdRoute
}

const CargoRouteChildren: CargoRouteChildren = {
  CargoIdRoute: CargoIdRoute,
}

const CargoRouteWithChildren = CargoRoute._addFileChildren(CargoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargoRoute: CargoRouteWithChildren,
  LoginRoute: LoginRoute,
  PackageRoute: PackageRoute,
  WarehouseRoute: WarehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
